name: autoupdate
on:
  push:
    branches:
      - main
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-24.04
    steps:
      - uses: chinthakagodawita/autoupdate@v1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
